-- ============================================================
-- SCRIPT DE DADOS INICIAIS - BARRA BONITA TURISMO
-- Gerado automaticamente em 23/06/2026 21:29:07
-- Execute este script UMA ÚNICA VEZ após criar o banco.
-- ============================================================

USE barrabonita;

-- ── Atrações ──────────────────────────────────────────────────
INSERT INTO Attractions (Name, Description, Category, ImageUrl, Address, Schedule, Latitude, Longitude, FunFact) VALUES
('Passeios de Barco', 'Os passeios de barco representam a principal atividade turística de Barra Bonita e são considerados um dos maiores símbolos da cidade. As embarcações realizam trajetos pelo Rio Tietê, permitindo aos visitantes contemplar o Rio formado pela barragem, áreas verdes, pontes, marinas e toda a paisagem fluvial da região. Durante o passeio, os turistas podem acompanhar a movimentação da hidrovia e conhecer de perto a famosa Eclusa de Barra Bonita, experiência considerada única no interior paulista.', 'Náutica', 'https://bagagemdespachada.com/wp-content/uploads/2020/05/barco_passeio_rio_tiete-scaled-e1604590105256.jpg', 'Estrada do Rio, Km 5 - Barra Bonita/SP', 'Quinta a Domingo, das 8h às 18h', -22.501200, -48.545600, 'Os barcos turísticos passam pela famosa Eclusa de Barra Bonita!'),
('Orla Fluvial', 'A Orla Fluvial de Barra Bonita é um dos espaços mais visitados da cidade e reúne turismo, lazer e contato direto com o Rio Tietê. O espaço conta com calçadão, bancos, iluminação noturna, áreas arborizadas e vista privilegiada das embarcações turísticas.', 'Náutica', 'https://barrabonita.sp.gov.br/storage/turismo/pontos-turisticos/fmw6wneFGw.jpg', 'Avenida Rosa Zanela Petri - Barra Bonita/SP', 'Aberto diariamente, 24 horas', -22.491500, -48.556400, 'A orla é um dos locais mais frequentados da cidade durante o pôr do sol!'),
('Museu Municipal Luiz Saffi', 'O Museu Municipal Luiz Saffi preserva grande parte da memória histórica e cultural de Barra Bonita. O museu reúne fotografias antigas, documentos históricos, objetos culturais, móveis e itens relacionados ao crescimento econômico e turístico da região.', 'Cultura', 'https://c1.staticflickr.com/5/4904/46028552182_32ccaf5b9a_b.jpg', 'Rua Primeiro de Março, Centro - Barra Bonita/SP', 'Terça a Sábado, das 9h às 17h', -22.492100, -48.557100, 'O museu está instalado em um prédio histórico ligado à antiga ferrovia!'),
('Marina da Barra', 'Estrutura náutica localizada na orla turística de Barra Bonita, oferecendo suporte para embarcações de pequeno e médio porte, incluindo lanchas, jet-skis e veleiros. É um importante ponto de apoio para turistas que desejam explorar o Rio Tietê.', 'Náutica', 'https://macamp.com.br/guia/wp-content/uploads/2020/09/Apoio-RV-Marina-Vale-do-Tiete-Barra-Bonita8-scaled.jpg', 'Orla da Avenida Pedro Ometto, 674 - Barra Bonita/SP', 'Diariamente', -22.489500, -48.552000, 'A marina possui capacidade para até 80 embarcações.'),
('Píer e Atracadouro Municipal', 'Local destinado à atracação de pequenas embarcações e contemplação do Rio Tietê. Possui estrutura acessível e é bastante procurado para apreciar o pôr do sol.', 'Náutica', 'https://barrabonita.sp.gov.br/storage/noticias/esportes-e-lazer/h8ajukAUZN.jpg', 'Orla da Avenida Pedro Ometto - Barra Bonita/SP', 'Aberto diariamente', -22.490200, -48.554800, 'É considerado um dos melhores pontos para fotografar o Rio Tietê.'),
('Usina Hidrelétrica de Barra Bonita', 'Importante complexo energético localizado junto à barragem do Rio Tietê. Sua construção impulsionou o desenvolvimento da navegação e do turismo fluvial na região.', 'Náutica', 'https://static.brasilenergia.com.br/upload/2025/1/00e47a1bb8924ab78f55f97fecd2532a-770x0.jpg', 'Rodovia Jaú–São Manoel, s/n - Barra Bonita/SP', 'Visitação externa', -22.489000, -48.559000, 'A eclusa turística funciona integrada à estrutura da usina.'),
('Memorial do Rio Tietê', 'Espaço cultural dedicado à preservação da história, biodiversidade e importância econômica do Rio Tietê, reunindo painéis, maquetes, equipamentos náuticos e documentos históricos.', 'Cultura', 'https://static.wixstatic.com/media/6347c0_ada3b74a0834446f870ada9108ec9682~mv2.jpg/v1/fill/w_320,h_217,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/J6pYr0Vfug_edited_edited.jpg', 'Avenida Pedro Ometto, 467 - Barra Bonita/SP', 'Todos os dias, das 8h às 18h', -22.491000, -48.555000, 'Recebe cerca de 30 mil estudantes por ano em visitas educativas.'),
('Teatro Municipal Professora Zita de Marchi', 'Principal espaço cultural da cidade, recebendo apresentações de teatro, dança, música, festivais e eventos artísticos ao longo do ano.', 'Cultura', 'https://barrabonita.sp.gov.br/storage/prefeitura/predios-municipais/GyoBLLtpOe.jpg', 'Rua João Gerin, 222 - Vila Operária - Barra Bonita/SP', 'Conforme programação cultural', -22.494200, -48.558800, 'É palco de importantes festivais culturais da região.'),
('Praça da Marinha', 'Área arborizada na orla turística que reúne monumentos históricos da Marinha do Brasil e oferece vista privilegiada do Rio Tietê.', 'Natureza', 'https://conteudo.solutudo.com.br/wp-content/uploads/2022/01/2-2-1024x683.jpg', 'Avenida Rosa Zanela Petri - Barra Bonita/SP', 'Aberto diariamente', -22.490500, -48.555500, 'Possui equipamentos militares históricos expostos ao público.'),
('Praça do Teleférico', 'Parque turístico municipal com lago para pedalinhos, área de eventos, quiosques e o tradicional teleférico que atravessa o parque.', 'Lazer', 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/1f/06/e2/teleferico-de-barra-bonita.jpg?w=1200&h=-1&s=1', 'Orla Turística - Centro - Barra Bonita/SP', 'Aberto diariamente', -22.491800, -48.555600, 'O teleférico possui aproximadamente 700 metros de percurso.'),
('Minicidade da Criança', 'Espaço infantil localizado na orla turística com réplicas de construções, playground e atrações voltadas para crianças.', 'Lazer', 'https://barrabonita.sp.gov.br/storage/noticias/planejamento-urbano-e-obras/4A50aeSvMW.jpg', 'Praça do Teleférico - Barra Bonita/SP', 'Aberto diariamente', -22.491600, -48.555700, 'Abriga réplicas de construções em escala infantil.'),
('Praça da Juventude', 'Área de esportes e recreação com pista de skate, quadras, campos de areia, espaços de convivência e opções de alimentação.', 'Lazer', 'https://barrabonita.sp.gov.br/storage/noticias/planejamento-urbano-e-obras/EQlu8sa2FpNf6ZDeb8CkpAQuAiFhtNBcyBOPpkuQ.jpg', 'Orla da Avenida Pedro Ometto - Barra Bonita/SP', 'Aberto diariamente', -22.492400, -48.556000, 'É um dos principais pontos de encontro dos jovens da cidade.');

-- ── Eventos ─────────────────────────────────────────────────
-- (nenhum evento cadastrado)

-- ── FAQs ────────────────────────────────────────────────────
INSERT INTO FAQs (Question, Answer, `Order`) VALUES
('Qual a melhor época para visitar Barra Bonita?', 'A cidade é agradável o ano todo. O verão (dezembro a março) é ideal para atividades náuticas, enquanto o inverno (junho a agosto) tem temperaturas amenas para passeios ao ar livre.', 1),
('Como chegar a Barra Bonita?', 'A cidade está localizada a 280km de São Paulo, acesso pela Rodovia Marechal Rondon (SP-300) ou pela SP-191. Há também linhas de ônibus regulares da Viação Cometa e outras empresas.', 2),
('Precisa pagar para acessar o Rio?', 'Não, o acesso ao Rio e à Orla é gratuito. Apenas atividades como aluguel de barcos e passeios turísticos têm custo.', 3),
('Onde se hospedar?', 'A cidade conta com hotéis, pousadas e chalés às margens do Rio. Recomendamos o Hotel Barra Bonita Resort, Pousada do Rio e Recanto do Pescador.', 4),
('É permitido nadar no Rio?', 'A natação é permitida apenas em áreas designadas e com supervisão. Recomendamos usar os clubes e praias artificiais para maior segurança.', 5);

-- ── Guia Turístico ──────────────────────────────────────────
INSERT INTO GuideItems (Type, Name, Description, Address, Phone, Website, ImageUrl, Rating) VALUES
('Hospedagem', 'Hotel Barra Bonita Resort', 'Resort completo com piscinas, sauna, academia e acesso direto ao Rio.', 'Av. Beira Rio, 1000', '(14) 3604-1234', 'www.hotelbarrabonita.com', 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&q=80', 5),
('Hospedagem', 'Pousada do Rio', 'Aconchegante pousada familiar com vista para o Rio e café colonial.', 'Rua das Flores, 45', '(14) 3604-5678', 'www.pousadadorio.com', 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=400&q=80', 4),
('Hospedagem', 'Chalés Recanto do Pescador', 'Chalés rústicos com estrutura para pesca e churrasqueira.', 'Estrada do Rio, Km 3', '(14) 3604-9012', NULL, 'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=400&q=80', 4),
('Gastronomia', 'Restaurante Peixe Vivo', 'Especializado em peixes do Rio, com destaque para a moqueca e o peixe na telha.', 'Av. Marginal, 200', '(14) 3604-3456', 'www.peixevivo.com', 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400&q=80', 5),
('Gastronomia', 'Cantina Italiana Bella Vista', 'Massas caseiras e pizzas artesanais com vista panorâmica.', 'Rua Italia, 78', '(14) 3604-7890', NULL, 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400&q=80', 4),
('Gastronomia', 'Churrascaria do Rio', 'Rodízio de carnes nobres com buffet completo e música ao vivo aos finais de semana.', 'Av. Beira Rio, 500', '(14) 3604-2345', NULL, 'https://images.unsplash.com/photo-1558030006-450675393462?w=400&q=80', 5),
('Gastronomia', 'Café Colonial da Vó', 'Café colonial com mais de 30 opções de doces, salgados e bolos caseiros.', 'Praça Central, 12', '(14) 3604-6789', NULL, 'https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=400&q=80', 4),
('Atividades', 'Aluguel de Barcos e Jet-skis', 'Aluguel de lanchas, jet-skis, caiaques e pedalinhos.', 'Marina Barra Bonita, Av. Beira Rio', '(14) 3604-1111', 'www.marinabarra.com', 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&q=80', 5),
('Atividades', 'Passeio de Escuna', 'Passeio guiado pelo Rio com parada para banho e almoço.', 'Píer Turístico', '(14) 3604-2222', NULL, 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=400&q=80', 5),
('Atividades', 'Trilhas Ecológicas', 'Trilhas monitoradas com guias especializados e observação de aves.', 'Recanto Ecológico', '(14) 3604-3333', NULL, 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&q=80', 4),
('Atividades', 'Pesca Esportiva', 'Passeios de barco para pesca com equipamentos e iscas inclusos.', 'Pesqueiro do Rio', '(14) 3604-4444', NULL, 'https://images.unsplash.com/photo-1500909019491-73dc3c1f8086?w=400&q=80', 4);
