-- ============================================================
-- SCRIPT DE DADOS INICIAIS - BARRA BONITA TURISMO
-- Gerado automaticamente em 23/06/2026 21:56:27
-- Execute este script UMA ÚNICA VEZ após criar o banco.
-- ============================================================

USE barrabonita;

-- ── Atrações ──────────────────────────────────────────────────
INSERT INTO Attractions (Name, Description, Category, ImageUrl, Address, Schedule, Latitude, Longitude, FunFact) VALUES
('Passeios de Barco', 'Os passeios de barco representam a principal atividade turística de Barra Bonita e são considerados um dos maiores símbolos da cidade. As embarcações realizam trajetos pelo Rio Tietê, permitindo aos visitantes contemplar o Rio formado pela barragem, áreas verdes, pontes, marinas e toda a paisagem fluvial da região. Durante o passeio, os turistas podem acompanhar a movimentação da hidrovia e conhecer de perto a famosa Eclusa de Barra Bonita, experiência considerada única no interior paulista.', 'Náutica', 'https://bagagemdespachada.com/wp-content/uploads/2020/05/barco_passeio_rio_tiete-scaled-e1604590105256.jpg', 'Estrada do Rio, Km 5 - Barra Bonita/SP', 'Quinta a Domingo, das 8h às 18h', -22.501200, -48.545600, 'Os barcos turísticos passam pela famosa Eclusa de Barra Bonita!'),
('Orla Fluvial', 'A Orla Fluvial de Barra Bonita é um dos espaços mais visitados da cidade e reúne turismo, lazer e contato direto com o Rio Tietê. O espaço conta com calçadão, bancos, iluminação noturna, áreas arborizadas e vista privilegiada das embarcações turísticas.', 'Náutica', 'https://barrabonita.sp.gov.br/storage/turismo/pontos-turisticos/fmw6wneFGw.jpg', 'Avenida Rosa Zanela Petri - Barra Bonita/SP', 'Aberto diariamente, 24 horas', -22.491500, -48.556400, 'A orla é um dos locais mais frequentados da cidade durante o pôr do sol!'),
('Museu Municipal Luiz Saffi', 'O Museu Municipal Luiz Saffi preserva grande parte da memória histórica e cultural de Barra Bonita. O museu reúne fotografias antigas, documentos históricos, objetos culturais, móveis e itens relacionados ao crescimento econômico e turístico da região.', 'Cultura', 'https://c1.staticflickr.com/5/4904/46028552182_32ccaf5b9a_b.jpg', 'Rua Primeiro de Março, Centro - Barra Bonita/SP', 'Terça a Sábado, das 9h às 17h', -22.492100, -48.557100, 'O museu está instalado em um prédio histórico ligado à antiga ferrovia!'),
('Marina da Barra', 'Estrutura náutica localizada na orla turística de Barra Bonita, oferecendo suporte para embarcações de pequeno e médio porte, incluindo lanchas, jet-skis e veleiros. É um importante ponto de apoio para turistas que desejam explorar o Rio Tietê.', 'Náutica', 'https://macamp.com.br/guia/wp-content/uploads/2020/09/Apoio-RV-Marina-Vale-do-Tiete-Barra-Bonita8-scaled.jpg', 'Orla da Avenida Pedro Ometto, 674 - Barra Bonita/SP', 'Diariamente', -22.489500, -48.552000, 'A marina possui capacidade para até 80 embarcações.'),
('Píer e Atracadouro Municipal', 'Local destinado à atracação de pequenas embarcações e contemplação do Rio Tietê. Possui estrutura acessível e é bastante procurado para apreciar o pôr do sol.', 'Náutica', 'https://barrabonita.sp.gov.br/storage/noticias/esportes-e-lazer/h8ajukAUZN.jpg', 'Orla da Avenida Pedro Ometto - Barra Bonita/SP', 'Aberto diariamente', -22.490200, -48.554800, 'É considerado um dos melhores pontos para fotografar o Rio Tietê.'),
('Usina Hidrelétrica de Barra Bonita', 'Importante complexo energético localizado junto à barragem do Rio Tietê. Sua construção impulsionou o desenvolvimento da navegação e do turismo fluvial na região.', 'Náutica', 'https://static.brasilenergia.com.br/upload/2025/1/00e47a1bb8924ab78f55f97fecd2532a-770x0.jpg', 'Rodovia Jaú–São Manoel, s/n - Barra Bonita/SP', 'Visitação externa', -22.489000, -48.559000, 'A eclusa turística funciona integrada à estrutura da usina.'),
('Memorial do Rio Tietê', 'Espaço cultural dedicado à preservação da história, biodiversidade e importância econômica do Rio Tietê, reunindo painéis, maquetes, equipamentos náuticos e documentos históricos.', 'Cultura', 'https://static.wixstatic.com/media/6347c0_ada3b74a0834446f870ada9108ec9682~mv2.jpg/v1/fill/w_320,h_217,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/J6pYr0Vfug_edited_edited.jpg', 'Avenida Pedro Ometto, 467 - Barra Bonita/SP', 'Todos os dias, das 8h às 18h', -22.491000, -48.555000, 'Recebe cerca de 30 mil estudantes por ano em visitas educativas.'),
('Teatro Municipal Professora Zita de Marchi', 'Principal espaço cultural da cidade, recebendo apresentações de teatro, dança, música, festivais e eventos artísticos ao longo do ano.', 'Cultura', 'https://barrabonita.sp.gov.br/storage/prefeitura/predios-municipais/GyoBLLtpOe.jpg', 'Rua João Gerin, 222 - Vila Operária - Barra Bonita/SP', 'Conforme programação cultural', -22.494200, -48.558800, 'É palco de importantes festivais culturais da região.'),
('Praça da Marinha', 'Área arborizada na orla turística que reúne monumentos históricos da Marinha do Brasil e oferece vista privilegiada do Rio Tietê.', 'Natureza', 'https://conteudo.solutudo.com.br/wp-content/uploads/2022/01/2-2-1024x683.jpg', 'Avenida Rosa Zanela Petri - Barra Bonita/SP', 'Aberto diariamente', -22.490500, -48.555500, 'Possui equipamentos militares históricos expostos ao público.'),
('Praça do Teleférico', 'Parque turístico municipal com lago para pedalinhos, área de eventos, quiosques e o tradicional teleférico que atravessa o parque.', 'Lazer', 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/1f/06/e2/teleferico-de-barra-bonita.jpg?w=1200&h=-1&s=1', 'Orla Turística - Centro - Barra Bonita/SP', 'Aberto diariamente', -22.491800, -48.555600, 'O teleférico possui aproximadamente 700 metros de percurso.'),
('Minicidade da Criança', 'Espaço infantil localizado na orla turística com réplicas de construções, playground e atrações voltadas para crianças.', 'Lazer', 'https://barrabonita.sp.gov.br/storage/noticias/planejamento-urbano-e-obras/4A50aeSvMW.jpg', 'Praça do Teleférico - Barra Bonita/SP', 'Aberto diariamente', -22.497500, -48.563300, 'Abriga réplicas de construções em escala infantil.'),
('Praça da Juventude', 'Área de esportes e recreação com pista de skate, quadras, campos de areia, espaços de convivência e opções de alimentação.', 'Lazer', 'https://barrabonita.sp.gov.br/storage/noticias/planejamento-urbano-e-obras/EQlu8sa2FpNf6ZDeb8CkpAQuAiFhtNBcyBOPpkuQ.jpg', 'Orla da Avenida Pedro Ometto - Barra Bonita/SP', 'Aberto diariamente', -22.492400, -48.556000, 'É um dos principais pontos de encontro dos jovens da cidade.');

-- ── Eventos ─────────────────────────────────────────────────
INSERT INTO Events (Title, Description, StartDate, EndDate, Location, ImageUrl, Color, IsFeatured, EventType) VALUES
('Festa Junina / Quermesses', 'Festas juninas organizadas por igrejas, escolas e entidades locais com comidas típicas, música e atividades comunitárias.', '2026-06-01', '2026-06-30', 'Diversos pontos da cidade (principalmente paróquias e escolas)', NULL, '#D97706', 1, 'Cultural');

-- ── FAQs ────────────────────────────────────────────────────
INSERT INTO FAQs (Question, Answer, `Order`) VALUES
('Qual a melhor época para visitar Barra Bonita?', 'A cidade é agradável o ano todo. O verão (dezembro a março) é ideal para atividades náuticas, enquanto o inverno (junho a agosto) tem temperaturas amenas para passeios ao ar livre.', 1),
('Como chegar a Barra Bonita?', 'A cidade está localizada a 280km de São Paulo, acesso pela Rodovia Marechal Rondon (SP-300) ou pela SP-191. Há também linhas de ônibus regulares da Viação Cometa e outras empresas.', 2),
('Precisa pagar para acessar o Rio?', 'Não, o acesso ao Rio e à Orla é gratuito. Apenas atividades como aluguel de barcos e passeios turísticos têm custo.', 3),
('Onde se hospedar?', 'A cidade conta com hotéis, pousadas e chalés às margens do Rio. Recomendamos o Hotel Barra Bonita Resort, Pousada do Rio e Recanto do Pescador.', 4),
('É permitido nadar no Rio?', 'A natação é permitida apenas em áreas designadas e com supervisão. Recomendamos usar os clubes e praias artificiais para maior segurança.', 5);

-- ── Guia Turístico ──────────────────────────────────────────
INSERT INTO GuideItems (Type, Name, Description, Address, Phone, Website, ImageUrl, Rating) VALUES
('Hospedagem', 'Hotel Estância', 'O Hotel Estância Barra Bonita é um resort no interior de São Paulo conhecido pela ampla área verde, piscinas aquecidas e estrutura de lazer para famílias. O hotel oferece chalés confortáveis, parque aquático com toboáguas, quadras esportivas, recreação infantil e restaurante com refeições em estilo buffet. É um destino bastante procurado para descanso, férias e eventos corporativos.', NULL, NULL, NULL, 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0d/6b/64/88/hotel-estancia-barra.jpg?w=900&h=-1&s=1', 5),
('Hospedagem', 'Hotel Barra Bonita', 'Hotel turístico urbano e tradicional de Barra Bonita, localizado na região central da cidade, próximo ao rio Tietê, à eclusa turística e aos principais pontos gastronômicos e comerciais. É bastante procurado por turistas, famílias e visitantes de negócios devido à localização estratégica e ao fácil acesso às atrações turísticas da estância. O empreendimento oferece hospedagem prática e confortável, com ambiente familiar e estrutura voltada ao turismo regional. É considerado uma importante referência de hospedagem da cidade, atendendo visitantes que buscam lazer, passeios fluviais e estadias de curta permanência.', NULL, NULL, NULL, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwHotGCAm3sj3whS_3Az7dK1c4P9CIMz6OuxA-5gPYaHI6hH_3alJs3UE&s=10', 5),
('Hospedagem', 'Hotel Beira Rio', 'Hotel tradicional e bastante conhecido de Barra Bonita, localizado às margens do rio Tietê e próximo aos principais pontos turísticos da cidade. Destaca-se pela localização privilegiada, com fácil acesso aos passeios fluviais, à eclusa turística e à região gastronômica central. É muito utilizado por turistas e visitantes que buscam praticidade, turismo regional e contato com o cenário turístico da estância.', NULL, NULL, NULL, 'https://barrabonita.sp.gov.br/storage/turismo/hoteis-e-pousadas/n0pWJyxI3z.jpg', 4),
('Gastronomia', 'Restaurante Estação da Barra', 'O Restaurante Estação da Barra, localizado em Barra Bonita (SP), é um estabelecimento inserido no setor de serviços de alimentação fora do lar, voltado ao fornecimento de refeições completas para o público local e turístico. Seu funcionamento concentra-se principalmente no serviço de almoço, com cardápio baseado na culinária brasileira, reunindo preparações que combinam aspectos tradicionais e contemporâneos. O restaurante caracteriza-se pela oferta de pratos variados e acessíveis, atendendo à demanda por refeições cotidianas e executivas. Assim, integra o segmento de restauração, desempenhando papel importante no atendimento gastronômico da região.', NULL, NULL, NULL, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWjlUfdKdz6v9t8zzrnUMPDvFaRz0br2AX7HF83M0P54xPHWmK6MCg_mTr&s=10', 4),
('Gastronomia', 'Barbina', 'A Barbina é um estabelecimento do segmento de gastronomia comercial que integra restaurante e choperia, caracterizando-se como um espaço voltado à alimentação e ao convívio social. Seu funcionamento combina a oferta de refeições, petiscos e porções com o serviço de bebidas, especialmente chopp, atendendo a diferentes momentos de consumo, como refeições e encontros de lazer. O empreendimento destaca-se por seu caráter híbrido entre restaurante e bar, inserindo-se na gastronomia de lazer e socialização, sendo frequentado tanto por moradores locais quanto por visitantes da região de Barra Bonita.', NULL, NULL, NULL, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0ZvovuwJCXDPqtllt2IGHEb44x_g-2ooZlghkQCsKDsbg_4dcwWGu7x0&s=10', 4),
('Gastronomia', 'Restaurante da Nilzete', 'O Restaurante da Nilzete, localizado em Barra Bonita (SP), é um estabelecimento do segmento de alimentação que se destaca pela oferta de refeições com características da culinária caseira e atendimento voltado ao público local e turístico. Situado na região central da cidade, o restaurante tornou-se uma opção tradicional para consumidores que buscam praticidade, variedade e bom custo-benefício. Seu cardápio reúne refeições completas, lanches e salgados, atendendo diferentes perfis de consumo ao longo do dia. Reconhecido pelas porções fartas e pelo ambiente acolhedor, o estabelecimento integra o cenário gastronômico regional como uma alternativa de alimentação cotidiana e turismo local.', NULL, NULL, NULL, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRU4ZJbFaRyaNrQg9PpdgoYksN21n5O2_nPHUCayMeOpHhhlH8nXHHajsc&s=10', 5);
