// <auto-generated />
using System;
using BarraBonitaTurismo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace BarraBonitaTurismo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BarraBonitaTurismo.Models.Attraction", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("varchar(200)");
                b.Property<string>("Description").IsRequired().HasColumnType("longtext");
                b.Property<string>("Category").IsRequired().HasMaxLength(50).HasColumnType("varchar(50)");
                b.Property<string>("ImageUrl").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<string>("Address").HasMaxLength(300).HasColumnType("varchar(300)");
                b.Property<string>("Schedule").HasMaxLength(200).HasColumnType("varchar(200)");
                b.Property<double?>("Latitude").HasColumnType("double");
                b.Property<double?>("Longitude").HasColumnType("double");
                b.Property<string>("FunFact").HasMaxLength(500).HasColumnType("varchar(500)");
                b.HasKey("Id");
                b.ToTable("Attractions");
            });

            modelBuilder.Entity("BarraBonitaTurismo.Models.ContactMessage", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("varchar(200)");
                b.Property<string>("Subject").IsRequired().HasMaxLength(200).HasColumnType("varchar(200)");
                b.Property<string>("Message").IsRequired().HasMaxLength(1000).HasColumnType("varchar(1000)");
                b.Property<DateTime>("SentAt").HasColumnType("datetime(6)");
                b.Property<bool>("IsRead").HasColumnType("tinyint(1)");
                b.HasKey("Id");
                b.ToTable("ContactMessages");
            });

            modelBuilder.Entity("BarraBonitaTurismo.Models.Event", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("varchar(200)");
                b.Property<string>("Description").IsRequired().HasColumnType("longtext");
                b.Property<DateTime>("StartDate").HasColumnType("datetime(6)");
                b.Property<DateTime?>("EndDate").HasColumnType("datetime(6)");
                b.Property<string>("Location").HasMaxLength(200).HasColumnType("varchar(200)");
                b.Property<string>("ImageUrl").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<bool>("IsFeatured").HasColumnType("tinyint(1)");
                b.Property<string>("EventType").HasMaxLength(50).HasColumnType("varchar(50)");
                b.HasKey("Id");
                b.ToTable("Events");
            });

            modelBuilder.Entity("BarraBonitaTurismo.Models.FAQ", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Question").IsRequired().HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<string>("Answer").IsRequired().HasColumnType("longtext");
                b.Property<int>("Order").HasColumnType("int");
                b.HasKey("Id");
                b.ToTable("FAQs");
            });

            modelBuilder.Entity("BarraBonitaTurismo.Models.GuideItem", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Type").IsRequired().HasMaxLength(50).HasColumnType("varchar(50)");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("varchar(200)");
                b.Property<string>("Description").HasColumnType("longtext");
                b.Property<string>("Address").HasMaxLength(300).HasColumnType("varchar(300)");
                b.Property<string>("Phone").HasMaxLength(20).HasColumnType("varchar(20)");
                b.Property<string>("Website").HasMaxLength(200).HasColumnType("varchar(200)");
                b.Property<string>("ImageUrl").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<int>("Rating").HasColumnType("int");
                b.HasKey("Id");
                b.ToTable("GuideItems");
            });
#pragma warning restore 612, 618
        }
    }
}
